---
# Shadowsocks Download variables
# ------------------------------
shadowsocks_mirror_location: "{{ streisand_mirror_location }}/shadowsocks"
shadowsocks_mirror_href_base: "/mirror/shadowsocks"

# Android
shadowsocks_android_version: "5.1.3"
shadowsocks_android_filename: "shadowsocks-nightly-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_android_filename }}"
shadowsocks_android_url: "https://github.com/shadowsocks/shadowsocks-android/releases/download/v{{ shadowsocks_android_version }}/shadowsocks--universal-{{ shadowsocks_android_version }}.apk"
shadowsocks_android_checksum: "sha256:52bd7200547713c9305483e1b6e526258801c79aec6888771234d82e6b875c3a"

# Windows
shadowsocks_gui_version: "4.1.9.2"
shadowsocks_gui_filename: "Shadowsocks-{{ shadowsocks_gui_version }}.zip"
shadowsocks_gui_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_url: "https://github.com/shadowsocks/shadowsocks-windows/releases/download/{{ shadowsocks_gui_version }}/{{ shadowsocks_gui_filename }}"
shadowsocks_gui_checksum: "sha256:7a52b4827a4dac14ccd0c8a05a46c7debafca33672285e7630ee8f8e54387738"

# macOS
shadowsocks_x_ng_version: "1.9.4"
shadowsocks_x_ng_filename: "ShadowsocksX-NG.{{ shadowsocks_x_ng_version }}.zip"
shadowsocks_x_ng_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_url: "https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v{{ shadowsocks_x_ng_version }}/{{ shadowsocks_x_ng_filename }}"
shadowsocks_x_ng_checksum: "sha256:dc06a995b63f8e32be9b86c265fd2979a6d73d4742d0ff16e1b2bb8f538d77a3"

# Linux (x64)
# NOTE(@cpu): if 32bit Linux clients are to be supported then we should add `shadowsocks2-linux-x86.gz`
shadowsocks_go_version: "0.1.3"
shadowsocks_go_filename: "shadowsocks2-linux.gz"
shadowsocks_go_href: "{{ shadowsocks_mirror_href_base }}/{{ shadowsocks_go_filename }}"
shadowsocks_go_url: "https://github.com/shadowsocks/go-shadowsocks2/releases/download/v{{ shadowsocks_go_version }}/{{ shadowsocks_go_filename }}"
shadowsocks_go_checksum: "sha256:d8c63767c1ce68292ac335e3ddaad921c1a6b49a3c7bd1c3864617ba9f46d3c2"

shadowsocks_download_urls:
  - { url: "{{ shadowsocks_android_url }}", checksum: "{{ shadowsocks_android_checksum }}" }
  - { url: "{{ shadowsocks_gui_url }}",     checksum: "{{ shadowsocks_gui_checksum }}" }
  - { url: "{{ shadowsocks_x_ng_url }}",    checksum: "{{ shadowsocks_x_ng_checksum }}" }
  - { url: "{{ shadowsocks_go_url }}",      checksum: "{{ shadowsocks_go_checksum }}" }
